const SPRITE_SCALE = 8;

export const config = {
    SPRITE_SCALE: SPRITE_SCALE,
    INTERNAL_WIDTH: 128, 
    INTERNAL_HEIGHT: 112,
    GAME_WIDTH: 128 * SPRITE_SCALE,
    GAME_HEIGHT: 112 * SPRITE_SCALE,
    PADDING: 16,
    HUD_Z: 100
}
